### ISSUE TITLE
4.1: Announce Presence: IP-address is available from UDP receiver

### ISSUE THREAD

**Issue by chrberger** [DIT168-V2V-responsibles/v2v-protocol#10]
The use of field https://github.com/DIT168-V2V-responsibles/v2v-protocol/blob/master/Messages.odvd#L2 is unclear as the UDPReceiver will provide the sender information: https://wandbox.org/permlink/3bWexUDo6OqxDCBE

**Comment by timjon** [comment]
We are using an od4 session to send the announce presence which to our knowledge doesnt have a way to get the ip. The reason for this is that we need the ip to connect the follower to the leader since we are using udp for that, so we need the ip before UDPReceiver starts.

**Comment by maansaake** [comment]
Issue resolved by last comment.
