### ISSUE TITLE
FollowRequest has no fields?

### ISSUE THREAD

**Issue by chrberger** [DIT168-V2V-responsibles/v2v-protocol#11]
The message FollowRequest does not contain any fields (https://github.com/DIT168-V2V-responsibles/v2v-protocol/blob/master/Messages.odvd#L7); do you just check whether it has been sent?

**Comment by timjon** [comment]
The followRequest and followResponse are used to do a handshake between the leader and follower and the only thing the leader needs from the follower is the ip which is extracted from the sender parameter of the UDPReceiver.

**Comment by chrberger** [comment]
Okay, I see

**Comment by kosara-g** [comment]
Resolved.
