### ISSUE TITLE
NTP server

### ISSUE THREAD

**Issue by chrberger** [DIT168-V2V-responsibles/v2v-protocol#12]
Message FollowResponse (https://github.com/DIT168-V2V-responsibles/v2v-protocol/blob/master/Messages.odvd#L11) provides details about an NTP server; you can just use time.google.com on all cars in your NTP client (https://help.ubuntu.com/lts/serverguide/NTP.html) and it should be fine.

**Comment by timjon** [comment]
The details about the NTP server is being removed in pull request #15

**Comment by chrberger** [comment]
Okay

**Comment by kosara-g** [comment]
Resolved in PR #15.
