### ISSUE TITLE
Message leakage to other motor proxies

### ISSUE THREAD

**Issue by maansaake** [DIT168-V2V-responsibles/v2v-protocol#16]
Since all cars currently operate using the same CID (111) for their motor proxies, all cars will essentially send all other cars actuating messages if they themselves want to increase/decrease their speed (or change steering angle).

**Comment by maansaake** [comment]
What we need to do is to define ranges for OD4Sessions for each group where they can place whatever they want. This to prevent signal leakage between vehicles. The only general channel that everyone should listen on is 200 for AnnouncePresence messages.

**Comment by chrberger** [comment]
You can also change the CID for interfacing with the motor in the docker-compose.yml file that you got from Yue and Federico.
