### ISSUE TITLE
Do not use raw pointers (new)

### ISSUE THREAD

**Issue by chrberger** [DIT168-V2V-responsibles/v2v-protocol#5]
The direct use of raw pointers created with `new` bear the risk of leaking memory. Thus, better create only wrapped pointers:

```
#include <memory>
shared_ptr<MyClass> ptrToMyClass = std::make_shared<MyClass>();
...
```
cf. http://en.cppreference.com/w/cpp/memory/shared_ptr/make_shared

**Comment by maansaake** [comment]
This issue has been addressed in [this](https://github.com/DIT168-V2V-responsibles/v2v-protocol/commit/c8d3e26d0aacd7bd9961a37c1e89a5d0cc312bd3) commit.
