### ISSUE TITLE
Make sure that your message IDs don't collide with the ones in use for accessing the vehicle's acceleration/steering

### ISSUE THREAD

**Issue by chrberger** [DIT168-V2V-responsibles/v2v-protocol#6]
https://github.com/DIT168-V2V-responsibles/v2v-protocol/blob/master/Messages.odvd#L1

**Comment by maansaake** [comment]
This issues has been resolved in [this](https://github.com/DIT168-V2V-responsibles/v2v-protocol/commit/7d60f5338bd5804d5b2199e106efb179ce39ef89) commit
