### ISSUE TITLE
Avoid "busy"-waits

### ISSUE THREAD

**Issue by chrberger** [DIT168-V2V-responsibles/v2v-protocol#7]
This part of your code will cause a "busy" wait and thus, cause a high system load: https://github.com/DIT168-V2V-responsibles/v2v-protocol/blob/master/Receiver.cpp#L48

Consider using:

```
std::this_thread::sleep_for(std::chrono::milliseconds(XYZ));
```

**Comment by maansaake** [comment]
This issue has been resolved in [this](https://github.com/DIT168-V2V-responsibles/v2v-protocol/commit/0651e3e425f11f88cc58a68f058916ce5009d3ef) commit.
